Popup project detail
kamranasif506/Portfolio pull request #11
Opened 2023-05-16 15:52 UTC by kamranasif506

- [ ] Popup box for project detail added

2023-05-16 16:24 UTC, V-Blaze requested changes
## Hi @kamranasif506 , 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![almost-there](https://user-images.githubusercontent.com/107632780/229242540-644ade4a-fe15-4f4c-a38b-6ded70cc4e8b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Popup works great✔
- Branch name is descriptive👋 
-  Correct linters setup✔

 ## Required Changes ♻️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-16 16:24 UTC, V-Blaze commented on index.html
>              </div>
- [ ] Your pop-up works great and looks like the given design. :+1: :taco: , But I think there are some requirements you need to meet before moving to the next milestone. Currently you still have the hard-coded project list in your index.html file, But according to the project requirement, both your project list and their details popup need to be generated dynamically. :+1:  I'll suggest you remove the HTML code in the project section and then dynamically display the list of projects on the home page from the array of project once the page loads. :smile: :smile: 

> You need to update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads.

2023-05-16 16:24 UTC, V-Blaze commented on script.js
> +    // }
- [ ] I'll suggest you remove this as leaving a commented piece of code in your project makes it look unprofessional and it's against the best practices. :smile: :+1:

2023-05-16 16:24 UTC, V-Blaze commented on script.js
> +// }
- [ ] I'll suggest you remove this as leaving a commented piece of code in your project makes it look unprofessional and it's against the best practices. :smile: :+1:

2023-05-17 06:30 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @kamranasif506, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 

- Descriptive Pull Request title and summary. ✔️
- User clicks the button, the popup with details about the project appears ✔️
- User clicks the close (X) button, the popup disappears ✔️
- Modal popup data is populated with the data from the projects array ✔️
- Good use of Github flow ✔️

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 06:30 UTC, brainconnect93 commented on index.html
> +        </div>
- [ ] Hello @kamranasif506, great effort working on the changes requested by the previous reviewer, But according to the reviewer, you were asked to make the project cards and the popup project details dynamic and also remove the hard coded line of code from your HTML file. But i noticed you only remove the code for the project cards while the code for the details popup is still in your HTML file. Kindly remove it and be sure it is created dynamically too.

Previous reviewer's comment 👇 

<img width="595" alt="image" src="https://github.com/kamranasif506/Portfolio/assets/78634841/355cc1ea-77e0-4dfb-958b-c50e3b9323e7">

2023-05-17 07:41 UTC, mikethreels approved these changes
Hi Kamran, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### I highly recommend having a look at the optional requirements, your code is approved now but for future projects, you will have to make the JS code dynamic in addition to the new skills you're going to learn, this will be good practice in order to make your future projects easier to understand and create.

## Highlights
- linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 07:41 UTC, mikethreels commented on script.js
> +const techHtml6 = tech6.map((item) => `<li>${item}</li>`).join('');
- [ ] [OPTIONAL] Because this wasn't mentioned by the previous CR this is not a requirement, however, you're repeating a lot of code here which is not in line with the general requirements. In addition to that if you would decide to add a project to your portfolio it is a lot more work than just adding it to your project array, you will need to change your code as well. if you would use a loop here this can be avoided.
- [ ] [OPTIONAL] You have the same issue with a lot of the other JS code, the fact that it is written in JS doesn't make it dynamic, it becomes dynamic when you solve the issues you would run into when coding with plain HTML, like repeating code and not being able to add to your code without making a lot of changes to it.

2023-05-17 08:58 UTC, merged