Contact form feature
kamranasif506/Portfolio pull request #4
Opened 2023-05-02 18:59 UTC by kamranasif506

Following features have been added

- [ ] Contact Us form
- [ ] Footer

2023-05-02 19:43 UTC, stanleySimeon requested changes
# Hi @kamranasif506, @Zafron047 
 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media2.giphy.com/media/vQGBDTkhtIunaJYmRF/giphy-downsized.gif?cid=29caca75sf3uq9y4qgulk5ybbojwg94b4zo6temfzeel417x&ep=v1_gifs_search&rid=giphy-downsized.gif&ct=g
)

## Highlights
- Correct use of Gitflow ✔️
- Linter checks are passed ✔️
- Good PR description ✔️
- Meaningful commit messages ✔️

# Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers, and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @stanleySimeon in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 19:43 UTC, stanleySimeon commented on index.html
> +    </footer>
- [ ] Kindly I suggest you add a label for each input as shown in the Figma design.

- [ ] Kindly make sure the form is validated by using a correct `formspree` id. In your case I see the id is not complete, kindly fix that. 😄

<img width="307" alt="Screenshot 2023-05-02 at 15 34 33" src="https://user-images.githubusercontent.com/91237525/235767436-65b4df6d-04a5-4c5f-8dda-e76145002514.png">

- [ ] Kindly make sure you stick to the design templates in Figma as much as possible, this includes the font, colors, images, and spacing (margin/padding). Please follow this [link](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23-9&t=LVMtdwmoeA5knQai-0) to see the Figma template.

> ### The Figma design
>
><img width="220" alt="Screenshot 2023-05-02 at 15 39 48" src="https://user-images.githubusercontent.com/91237525/235768493-d915b1c0-be45-421c-aa1e-eabe54e31b80.png">
>
>### Your Design
>
><img width="305" alt="Screenshot 2023-05-02 at 15 40 34" src="https://user-images.githubusercontent.com/91237525/235768628-0ecaa594-373e-4044-acd9-b053c7b18de6.png">

2023-05-03 08:07 UTC, kamranasif506 commented on index.html
> +    </footer>
@stanleySimeon  Hello sir, i think there might be some mistake as this is not my design. can you please check it again.

2023-05-03 11:45 UTC, iambenkis approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @iambenkis in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 11:47 UTC, merged