Desktop design
kamranasif506/Portfolio pull request #5
Opened 2023-05-05 19:58 UTC by kamranasif506

following features have been made

- [ ] header section for desktop screen
- [ ] Hello section for desktop screen
- [ ] Project section for desktop screen
- [ ] About section for desktop screen
- [ ] Contact section for desktop screen
- [ ] Footer section for desktop screen

2023-05-05 21:55 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @kamranasif506 🙋‍♀️

Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in!  **_However, there are few things that still need to be fixed. But you are almost there!_** 💪 🏁

![so_close](https://user-images.githubusercontent.com/99715640/211022680-440a1bb1-4281-4acb-8dbc-3442fe509063.gif)

## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Well done so far following the given Figma design
- ✅ Great job with CSS
- ✅ Descriptive PR and README file
- ✅ Correct Linters

## Required Changes 🛑

> _Please keep in mind that your long hours of work is appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄_

_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 21:55 UTC, KanzaTahreem commented on style.css
> +
### _Desktop version_
- [ ] Please make sure to align this button with text to get a design close to Figma template ✌ See the images below 👇

Your design | Figma design
---| ---|
![image](https://user-images.githubusercontent.com/106119105/236560091-7ae72809-1e8a-423b-b635-dbfb7210f45d.png) | ![image](https://user-images.githubusercontent.com/106119105/236560176-f6150706-aace-469a-a541-97b39ec8807b.png)

2023-05-05 21:55 UTC, KanzaTahreem commented on style.css
> +  }
### _Desktop version_

- [ ] I think it would be better to increase the `font-size` of the following list. Maybe you can use `20px` to match the Figma template 🛠
- [ ] What do you think of increasing a bit of space between the list items and button, and reducing it between project name and list items 🤔✨
- [ ] I think it would be better to increase the height and reduce the width of the background a bit 😅 I think height can be fixed by increasing the `font-size`, so you can only reduce the `width` a bit 

Your design | Figma template
---| ---| 
![image](https://user-images.githubusercontent.com/106119105/236561426-82495e73-9655-450a-88b1-bd38cb22a7e7.png) | ![image](https://user-images.githubusercontent.com/106119105/236561529-3b84b061-26bf-468b-b088-5858af1dae49.png)

2023-05-05 21:55 UTC, KanzaTahreem commented on style.css
> +  }
### _Desktop version_

- [ ] Please increase the font size of list items a bit to get a design close to the Figma template 😄 and reduce a bit of space between project name and list items 

Your design | Figma template
---| ---|
![image](https://user-images.githubusercontent.com/106119105/236562880-d254728f-2a05-412a-8956-6d1a86da0e28.png) | ![image](https://user-images.githubusercontent.com/106119105/236563091-ca86904e-da8d-41d0-89c5-95dad8ceb30d.png)

2023-05-05 21:55 UTC, KanzaTahreem commented on style.css
>    }
### _Both versions_
- [ ] I think it would be better to add a bit of gap between the text and image. You can use the following for it

 ```
  display: flex;
  align-items: center;
  gap: 1rem;
```


Your design | Figma template 
---| ---|
![image](https://user-images.githubusercontent.com/106119105/236564355-9f29eb8f-70d8-4473-9669-3670bc47eae4.png) | ![image](https://user-images.githubusercontent.com/106119105/236564455-2c7b01c9-436b-4f29-8451-0f3db2eb41af.png)

2023-05-05 21:55 UTC, KanzaTahreem commented on index.html
> +      <div class="about_info">
### _Mobile version_

Please consider implementing the following for mobile version's About section 👇
- [ ] Increase the `font-size` of heading and use `font-weight: normal`
- [ ] Use `font-size: 14px;` for `p`
- [ ] Decrease the gap between `Get my CV` and `img`
- [ ] Use the given `colors`
- [ ] Use the same margin/padding/space as given in the Figma template.  

Your design | Figma design
---| ---|
![image](https://user-images.githubusercontent.com/106119105/236567997-b23e5a03-e948-4359-aca3-e6eb088ce90d.png) | ![image](https://user-images.githubusercontent.com/106119105/236568037-9c6f0f70-cf8c-4004-89b7-998b431a3071.png)

2023-05-05 21:55 UTC, KanzaTahreem commented on index.html
> +                  <ul class="langs inside_ul">
### _Mobile version_

- [ ] Right now, the Languages, Frameworks and Skills have more space/margin/padding on left than given in the design guidelines. Please make sure to reduce it. See the images below 👇


Your design | Figma design
---| ---|
![image](https://user-images.githubusercontent.com/106119105/236568706-bb442443-e5b0-4a9a-8a5b-a58c61623b1e.png) | ![image](https://user-images.githubusercontent.com/106119105/236568753-3124e4f5-0666-4456-aaa8-7e43773b6319.png)

2023-05-05 21:55 UTC, KanzaTahreem commented on index.html
> +        </p>
- [ ] Please make sure to use `font-size: 14px` for mobile version as given in the design guidelines.

2023-05-05 21:55 UTC, KanzaTahreem commented on style.css
> +  .get_cv {
- [ ] Please make sure to implement the `hover` and `active` button interactions for about section and "See this project" buttons ⚒😅

2023-05-05 21:55 UTC, KanzaTahreem commented on style.css
- [ ] Wile switching from mobile version to desktop version, the design is not responsive 😓 After `768px` there is some blank white space on right which is because of image on line 125. Also, the headline and about section elements are overlapping. Please make sure to fix these issues. The design works as expected after `1260+ px`. Kudos for that 🙌
_See the video below for more clarity 👇_



https://user-images.githubusercontent.com/106119105/236573355-e4107470-96dc-4a96-9fd4-e96f7c5a58d8.mp4


- [ ] Also, please make sure to remove commented code from `.css` file

2023-05-06 10:12 UTC, NatiG25 requested changes
## :yellow_circle: CHANGES REQUIRED :yellow_circle: 

## Hi @kamranasif506 :wave:, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Highlights
:heavy_check_mark: Great design! :rocket:.
:heavy_check_mark: Nicely done! Using Flexbox & Grid together.

![](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 10:12 UTC, NatiG25 commented on style.css
> +  }
- [ ] Kindly, make sure to reduce the bottom margin of the project's title, in order to, match the Figma design.

## Your design
![image](https://user-images.githubusercontent.com/86069740/236617851-fba6fa84-6d58-4e6d-98ad-a36a1d38fefe.png)

## Figma
![image](https://user-images.githubusercontent.com/86069740/236617869-f09d6e52-6e1e-4b13-804e-34e5c0a5d3cd.png)

2023-05-06 11:01 UTC, kamranasif506 commented on style.css
> +
Hello @NatiG25 Sir,
Thanks for the review and guidance.
I think the previous review was also that the design was not responsive after 768px and which i have resolved. (i checked on 2 different browsers and no empty space is left). 
And i think we only have to make responsiveness for above/after 768px. 
thats what i read about the project requirement. please let me know if i understand the requirements wrongly.
Thanks.

2023-05-06 13:30 UTC, AlphaNtihinduka approved these changes
# STATUS: APPROVED :green_circle: :clap: 
## Hi @kamranasif506 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- [ ] Please ensure that the mobile responsiveness is followed at all the screen sizes of mobile version. I have noticed that mobile version design is only followed at 375px and beyond that up to 768px, it is in desktop version format which does not match the Figma template design.
Your design at 500px😎 
![image](https://user-images.githubusercontent.com/99394374/236627281-2fc88181-1b89-4a13-872d-615ceb68c429.png)

- Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

2023-05-06 16:36 UTC, merged